env:
  browser: false
  node: true
  commonjs: true
  es2021: true
  jest: true
  jest/globals: true
parserOptions:
  ecmaVersion: 12
plugins:
  - jest
rules:
  indent:
    - warn
    - 2
  linebreak-style:
    - off
    - unix
  quotes:
    - warn
    - single
  semi:
    - warn
    - always
  no-var:
    - error
  eqeqeq:
    - warn
    - smart
  prefer-const:
    - warn
    - destructuring: all
extends:
  - 'eslint:recommended'
  - 'prettier'
