name: Expo Build

on: 
  pull_request:
    branches:
      - master
      - dev

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
          
      - name: Setup Expo
        uses: expo/expo-github-action@v5
        with:
          expo-version: 4.x
      
      - name: Install dependencies
        run: yarn install
        
      - name: Build App
        run: expo build:web --no-pwa

      - name: Run Tests
        run: yarn test
